// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTHZUlMno4MlBaloMrdxYH8wSU5HBw9Os',
    appId: '1:254801666464:web:d03e6783bce182401e84c5',
    messagingSenderId: '254801666464',
    projectId: 'payment-tracker-545e6',
    authDomain: 'payment-tracker-545e6.firebaseapp.com',
    storageBucket: 'payment-tracker-545e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPexJPLerNDxgA7h4yzzGkGylbh_uCCo',
    appId: '1:254801666464:android:784a2e24e3e1eb791e84c5',
    messagingSenderId: '254801666464',
    projectId: 'payment-tracker-545e6',
    storageBucket: 'payment-tracker-545e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUZrcCwDdIC9Rg7tz3SEieZhaC8KcdvQ',
    appId: '1:254801666464:ios:46f3cde2e62c68961e84c5',
    messagingSenderId: '254801666464',
    projectId: 'payment-tracker-545e6',
    storageBucket: 'payment-tracker-545e6.firebasestorage.app',
    iosBundleId: 'com.example.paymentTracker',
  );
}
